I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 196, in script
    $ _return = renpy.call_screen("action_choice_placeVillage"(lunette=_testLunettes, glaive=_testGlaive, bouclier=_testBouclier))
  File "game/script.rpy", line 196, in <module>
    $ _return = renpy.call_screen("action_choice_placeVillage"(lunette=_testLunettes, glaive=_testGlaive, bouclier=_testBouclier))
TypeError: 'unicode' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 196, in script
    $ _return = renpy.call_screen("action_choice_placeVillage"(lunette=_testLunettes, glaive=_testGlaive, bouclier=_testBouclier))
  File "D:\RenPy\renpy-6.99.12.4-sdk\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\RenPy\renpy-6.99.12.4-sdk\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 196, in <module>
    $ _return = renpy.call_screen("action_choice_placeVillage"(lunette=_testLunettes, glaive=_testGlaive, bouclier=_testBouclier))
TypeError: 'unicode' object is not callable

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Véléda - Pour Josiane et ces chers Germains 0.6
